package uk.ac.warwick.cs261.group41.airportmodellingproject.dto;

import jakarta.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Range;
import uk.ac.warwick.cs261.group41.airportmodellingproject.enums.RunwayMode;
import uk.ac.warwick.cs261.group41.airportmodellingproject.enums.RunwayStatus;

public class RunwayConfig {
    // This ID is the index of the runway in the array, it is generated by the JS frontend so doesn't really need validation.
    // In future, could allow the user to name the runways and keep this ID as a backend identifier of each runway.
    @Range(min = 0, max = 9, message = "Runway ID must be between 0 and 9")
    private int runwayID;

    @NotNull(message = "Runway status must be specified (Available, Inspection, Snow Clearance, Mechanical Failure)")
    private RunwayStatus status;

    @NotNull(message = "Runway mode must be specified (Landing, Takeoff, Mixed)")
    private RunwayMode mode;

    // Default constructor required for Jackson to turn the JSON into this object.
    public RunwayConfig() {}

    // Parameterised constructor exclusively used for testing purposes.
    // USED IN EVENT SYSTEM (in order to get a snapshot of the previous runway before initiating an event)
    public RunwayConfig(int runwayID, RunwayStatus status, RunwayMode mode) {
        this.runwayID = runwayID;
        this.status = status;
        this.mode = mode;
    }

    public int getRunwayID() {
        return runwayID;
    }

    public void setRunwayID(int runwayID) {
        this.runwayID = runwayID;
    }

    public RunwayMode getMode() {
        return mode;
    }

    public void setMode(RunwayMode mode) {
        this.mode = mode;
    }

    public RunwayStatus getStatus() {
        return status;
    }

    public void setStatus(RunwayStatus status) {
        this.status = status;
    }
}
