package uk.ac.warwick.cs261.group41.airportmodellingproject.enums;

/**
 * Identifies the source that triggered an event in the simulation.
 * Used to track whether events were pre-planned, randomly generated, or user-initiated.
 */
public enum EventSource {
    /** No specific source - default state */
    NONE,
    
    /** Event was pre-scheduled in the simulation configuration */
    SCHEDULED,
    
    /** Event was randomly generated by the simulation engine */
    RANDOM,
    
    /** Event was manually triggered by the user during simulation */
    MANUAL
}
